using UnityEngine;
using UnityEngine.Events;

/// <summary>
/// Interaction trigger: completes an active goal when the player interacts and has that goal.
/// </summary>
[RequireComponent(typeof(Collider2D))]
public class GoalCompletionTrigger : InteractionTrigger
{
    [Header("Goal completion")]
    [Tooltip("The goal satisfied by this trigger (set in scene, or wired when a goal is generated by GoalAssignmentTrigger).")]
    public Goal goal;

    public Sprite goalIcon;

    [Header("Generated goal / navigation")]
    [Tooltip("When set, generated goals use this transform as Goal.locationSource. If null, generated goals snapshot GoalCompletionTrigger.transform.position into Goal.location.")]
    public Transform locationMarkerSource;

    [Header("Events")]
    public UnityEvent onCompletionSucceeded;
    [Tooltip("Fired when the player interacts but does not have the required goal.")]
    public UnityEvent onCompletionFailed;

    protected override void OnInteractInvoked(GameObject source, Vector2 contactPoint)
    {
        if (goal == null)
        {
            ResetTrigger();
            suppressActivationConsume = true;
            onCompletionFailed?.Invoke();
            return;
        }

        var player = source != null ? source.GetComponentInParent<PlayerControllerM>() : null;
        if (player != null && player.HasGoal(goal))
        {
            print("GoalCompletionTrigger: completing goal: " + goal.displayName);
            player.CompleteGoal(goal);
            onCompletionSucceeded?.Invoke();
        }
        else
        {
            ResetTrigger();
            suppressActivationConsume = true;
            onCompletionFailed?.Invoke();
        }
    }
}
